import Head from "next/head";
import { Text1 } from "../components/shared/Texts";


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Text1> abc </Text1>
      </main>
    </div>
  );
}
